### ISSUE TITLE
Sticher does not stich all images

### ISSUE THREAD

**Issue by NathanaelMangold** [Anders142536/imageStitcher#3]
I tried using the stitcher to stich my screenshots. However for some reason he ignores some images and does not stitch all of them together.

e.g.:
**The Stiched picture by the program:**
![AutoStitch](https://user-images.githubusercontent.com/41338825/148575884-8d8b073d-4baa-4a22-af28-9bd0e7fe3143.png)

**The Stiched picture I stiched quickly by myself:**
![ManualStitch](https://user-images.githubusercontent.com/41338825/148575907-4951c5ec-887d-4af5-8f22-dfc1b5a9cf86.png)

Is there any way to fis this?

**Comment by Anders142536** [comment]
this is weird and should not happen.
**Please send me the fragmented screenshots for this specific picture**, I will have a deeper look into it.

Were there any weird error messages shown whilst stitching it? The only issue I could think of right off the bat would be that one or more images are missing and my algorithm would be unable to deal with it. Images are stitched based on their file name, as there is no other way for me to mark them.

_Well, I could make a border or one extra pixel with each fragment and then fiddle them together based on that edge but that would take ages to implement compared to a x and y coordinate in the name_

**Comment by NathanaelMangold** [comment]
Thanks for the quick awnser. I'll do that, but I don't have access to the files until Monday!

Also in the docs you mention "The whole base is screenshotted until an unreasonably big base size is reached. "
How big is unreasonably big ?

**Comment by Anders142536** [comment]
Short answer:
![huge](https://tenor.com/view/lovesick-this-big-big-like-this-gif-19466516.gif)

Long answer:
The [take_screenshot](https://lua-api.factorio.com/latest/LuaGameScript.html#LuaGameScript.take_screenshot) method takes a zoom value. The higher this value, the smaller the image. [One tile in factorio is 32x32 pixels](https://wiki.factorio.com/Map_structure). A zoom value of 1 means its a 1:1 mapping. 2 means a 1:2 mapping (making the image effectively half the size with every tile being rendered with 16x16 pixels). A value of 4 means 1:4 (making the image a quarter the size, rendering every tile with 8x8 pixels) etc.
The highest value accepted by the method is 32 (unfortunatly undocumented).  This means that on the maximum zoom level every tile is reduced to 1 pixel.

This also means with the [current max resolution of 16k](https://github.com/Anders142536/FacAutoScreenshot/blob/bf2792d2c0aa55b9dfe4a3be5df8337129b63147/scripts/guibuilder.lua#L164) the maximum size you can screenshot is 15360x8640 tiles.

**Comment by Anders142536** [comment]
Oh, another fun fact:
A [tile translates to 1m in real life](https://wiki.factorio.com/Map_structure#Real_world_size_analogy), so that means the max size is 15.3km x 8.6km, or 137 km^2

**Comment by Anders142536** [comment]
Oh, and please be so kind to send me a copy of your save file as well, so i can test if there is an issue with the screenshot taking itself!

**Comment by NathanaelMangold** [comment]
That's indeed big enough, thanks 👍🏼

Yes, I will sent you everything on Sunday/Monday!

**Comment by NathanaelMangold** [comment]
Here are the files you need:

Thanks for any help :)

[SaveFile.zip](https://github.com/Anders142536/imageStitcher/files/7833108/SaveFile.zip)
[Stiched.zip](https://github.com/Anders142536/imageStitcher/files/7833109/Stiched.zip)
[RawScreenshots.zip](https://github.com/Anders142536/imageStitcher/files/7833112/RawScreenshots.zip)

**Comment by Anders142536** [comment]
I can reproduce the issue. I wont be able to further look into this before the weekend.

Is this happening with every screenshot or just this particular one?

**Comment by NathanaelMangold** [comment]
I'm not sure. I think it is with all pictures tho. I build myself a Python Script that does the same thing and with that it is working without any issues. I'll invite you to the repo if you wanna have a look at it. I think you are always missing 1 row and 1 colum to the far right.

**Comment by Anders142536** [comment]
I see. Weird, as i am very sure i tested this thoroughly. I guess i have to add a few more checks.

Thanks for the invite. Is the repo private on purpose? I could add a link to it in the Info page if the mod, so people could choose which one to use.

Python is preinstalled on basically every linux, which would make it more interesting for some people. My java program would probably be faster, but run everywhere java runs.

On the long run I wanted to rewrite the program in rust, as a learning project. It would be even faster again, but require compiled binaries for every platform afaik. Diversifying the possibilities would be great.

**Comment by NathanaelMangold** [comment]
That's indeed weird. Should be just a small change tho I think.

You had the same thought as me. I just build it in Python because I wanted to learn a way to process images in Python. But yes it would be great to link it to the mod page.

I'll try to finish the UI I worked on for it for non programing users and then I'll clean the repo up a bit and I will publish it!

**Comment by NathanaelMangold** [comment]
@Anders142536  FYI: I just finalized the repo and published it. You can link it now if you want to!

**Comment by Anders142536** [comment]
Nice. I linked it in the description. Thanks again.

I also added a summary about your question regarding maximum base sizes to the FAQ, in case anyone else is wondering.

**Comment by Anders142536** [comment]
@NathanaelMangold fixed. This was really a general issue with my screenshot stitching.

I plan to add a few unit tests to check this programmatically, but manually checking showed the bug should be fixed.

Again, thanks for reporting this!
